apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: ibn_docs
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ibn_docs
      sslmode: disable
