export type DocStatus =
  | "UPLOADED"
  | "VALIDATING"
  | "SPLITTING"
  | "OCR_PROCESSING"
  | "CLEANING"
  | "GENERATING"
  | "COMPLETED"
  | "FAILED"
  | "ARCHIVED";

export type ExportFormat = "md" | "txt" | "docx" | "json" | "pdf" | "epub";

export const DOC_STATUS_MAP: Record<string, DocStatus> = {
  pending: "UPLOADED",
  validating: "VALIDATING",
  splitting: "SPLITTING",
  ocr: "OCR_PROCESSING",
  cleaning: "CLEANING",
  generating: "GENERATING",
  completed: "COMPLETED",
  failed: "FAILED",
};

export const STATUS_LABELS: Record<DocStatus, string> = {
  UPLOADED: "تم الرفع",
  VALIDATING: "جاري التحقق",
  SPLITTING: "جاري التقسيم",
  OCR_PROCESSING: "جاري التعرف على النص",
  CLEANING: "جاري التنظيف",
  GENERATING: "جاري التوليد",
  COMPLETED: "مكتمل",
  FAILED: "فشل",
  ARCHIVED: "مؤرشف",
} as const;

export const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  RATE_LIMITED: "RATE_LIMITED",
  BAD_REQUEST: "BAD_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  FOLDER_NOT_FOUND: "FOLDER_NOT_FOUND",
  TAG_NOT_FOUND: "TAG_NOT_FOUND",
  TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
  NO_SHARE_LINK: "NO_SHARE_LINK",
  SOME_NOT_FOUND: "SOME_NOT_FOUND",
  SOME_TAGS_NOT_FOUND: "SOME_TAGS_NOT_FOUND",
  TAG_NOT_ASSIGNED: "TAG_NOT_ASSIGNED",
  PARENT_DELETED: "PARENT_DELETED",
  CIRCULAR_REFERENCE: "CIRCULAR_REFERENCE",
  MAX_DEPTH_REACHED: "MAX_DEPTH_REACHED",
  NOT_READY: "NOT_READY",
  AUTH_ERROR: "AUTH_ERROR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_TYPE: "INVALID_TYPE",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  PDF_SPLIT_FAILED: "PDF_SPLIT_FAILED",
  OCR_FAILED: "OCR_FAILED",
  OCR_QUOTA_EXCEEDED: "OCR_QUOTA_EXCEEDED",
  OCR_NO_TEXT: "OCR_NO_TEXT",
  CLEANUP_FAILED: "CLEANUP_FAILED",
  GENERATION_FAILED: "GENERATION_FAILED",
  EXPORT_FAILED: "EXPORT_FAILED",
  STORAGE_ERROR: "STORAGE_ERROR",
  PDF_ENCRYPTED: "PDF_ENCRYPTED",
  PDF_CORRUPT: "PDF_CORRUPT",
  PDF_TRUNCATED: "PDF_TRUNCATED",
  PDF_MALFORMED: "PDF_MALFORMED",
  JOB_TIMEOUT: "JOB_TIMEOUT",
  JOB_ABORTED: "JOB_ABORTED",
  RETRY_EXHAUSTED: "RETRY_EXHAUSTED",
  DLQ_REJECTED: "DLQ_REJECTED",
  ORPHAN_CLEANUP: "ORPHAN_CLEANUP",
  REDIS_CONNECTION: "REDIS_CONNECTION",
  MINIO_CONNECTION: "MINIO_CONNECTION",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const FAILURE_CATEGORIES = {
  TRANSIENT: "transient",
  PERMANENT: "permanent",
  FATAL: "fatal",
} as const;

export type FailureCategory = (typeof FAILURE_CATEGORIES)[keyof typeof FAILURE_CATEGORIES];
