import { NextResponse } from "next/server";
import { requireAuth, unauthorizedResponse } from "@/lib/auth-guards";
import { documentUseCases } from "@/core/use-cases/document.use-cases";
import { enqueueExport, loadConfig } from "@ibn-al-azhar-docs/pipeline";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await requireAuth().catch(() => null);
  if (!session) {
    return unauthorizedResponse();
  }

  const { id } = await params;

  let body: { format?: string; options?: Record<string, unknown> };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: { code: "BAD_REQUEST", message: "Invalid JSON" } },
      { status: 400 },
    );
  }

  const format = body.format;
  const options = body.options;

  if (!format || !["md", "txt", "docx", "epub", "json", "pdf", "searchable-pdf"].includes(format)) {
    return NextResponse.json(
      {
        error: {
          code: "VALIDATION_ERROR",
          message: "Format must be md, txt, docx, epub, json, pdf, or searchable-pdf",
        },
      },
      { status: 400 },
    );
  }

  try {
    // Check if document exists and is accessible
    const document = await documentUseCases.getDocumentById(id, session.user.id);

    if (document.status !== "COMPLETED") {
      return NextResponse.json(
        { error: { code: "BAD_REQUEST", message: "Document processing is not completed" } },
        { status: 400 },
      );
    }

    if (options?.destination === "drive") {
      const { prisma } = await import("@/lib/prisma");
      const account = await prisma.account.findFirst({
        where: { userId: session.user.id, provider: "google" },
      });
      if (!account || !account.access_token || !account.refresh_token) {
        return NextResponse.json(
          {
            error: {
              code: "NOT_LINKED",
              message:
                "يجب ربط حساب Google الخاص بك من الإعدادات أولاً لتتمكن من التصدير إلى Drive.",
            },
          },
          { status: 400 },
        );
      }
    }

    const config = loadConfig();

    // We can use the document ID as the jobId for the export request to group exports
    const jobId = document.id;

    const textKey = `${config.paths.ocrResults}/${document.id}/cleaned.json`;
    const outputKey = `${config.paths.exports}/${document.id}/export.${format}`;

    if (format === "searchable-pdf") {
      // Searchable PDF is already generated by OCR worker, no need to enqueue
      return NextResponse.json({ success: true, jobId: document.id, message: "Export ready" });
    }

    await enqueueExport(config, {
      jobId,
      documentId: document.id,
      userId: session.user.id,
      format: format as "md" | "txt" | "docx" | "epub" | "json" | "pdf",
      textKey,
      outputKey,
      pageCount: document.pageCount || undefined,
      options,
    });

    return NextResponse.json({ success: true, jobId, message: "Export job enqueued" });
  } catch (error: unknown) {
    if ((error as Error).message === "NOT_FOUND") {
      return NextResponse.json(
        { error: { code: "NOT_FOUND", message: "المستند غير موجود" } },
        { status: 404 },
      );
    }
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message: "حدث خطأ داخلي" } },
      { status: 500 },
    );
  }
}
